"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useLocale } from "next-intl";
import Link from "next/link";
import CustomerStageGoal from "./CustomerStageGoal";
import { uniqueStagePeople, emptyInsight, insightSchema, INSIGHT_STAGES, STAGE_CONFIG, CHALLENGES, type Insight, type InsightStage } from "@/lib/customer-insights/schema";
import { pathForLocale } from "@/lib/routes";
import type { Locale } from "@/i18n/routing";
import { notifyPlanChanged } from "./PlanRefresh";

import type { ActionPlanDto } from "@/lib/action-plan/service";

export default function CustomerDiscovery({ userId, rows, outcomes, actionId, readOnly = false, onSaved }: { actionId?: string; readOnly?: boolean; onSaved?: (plan?: ActionPlanDto) => void; userId: string; outcomes: { stage: string; primaryCount: number; secondaryCount: number; confirmedAt: string }[]; rows: { id: string; updatedAt: string; insight: unknown }[] }) {
  const locale = useLocale() as Locale, zh = locale === "zh-tw", lang = zh ? 1 : 0, router = useRouter();
  const blank = (stage: InsightStage): Insight => ({ ...emptyInsight(stage), ...(actionId ? { actionId } : {}) });
  const [form, setForm] = useState<Insight>(blank("discover")), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  const [conflict, setConflict] = useState(false);
  const [editing, setEditing] = useState<{ id: string; updatedAt: string } | null>(null);
  const requestId = useRef(""), sending = useRef(false), name = useRef<HTMLInputElement>(null);
  const key = `nova:discovery:${userId}${actionId ? `:${actionId}` : ""}`;
  useEffect(() => { const timer = setTimeout(() => { try { const local = JSON.parse(localStorage.getItem(key) || "null"); if (local?.form) { const parsed = insightSchema.safeParse({ ...local.form, name: local.form.name || "Draft" }); if (parsed.success && (!actionId || parsed.data.actionId === actionId)) { setForm({ ...parsed.data, name: local.form.name || "" }); if (typeof local.editing?.id === "string" && typeof local.editing?.updatedAt === "string") setEditing(local.editing); } } requestId.current = typeof local?.requestId === "string" ? local.requestId : crypto.randomUUID(); } catch { requestId.current = crypto.randomUUID(); setNotice(zh ? "無法恢復本機草稿，已儲存的紀錄仍保留。" : "Local draft could not be restored. Saved conversations are retained."); } setLoaded(true); }, 0); return () => clearTimeout(timer); }, [key, zh, actionId]);
  function change(next: Insight, edit = editing) { setForm(next); try { localStorage.setItem(key, JSON.stringify({ form: next, requestId: requestId.current, editing: edit })); } catch { setNotice(zh ? "無法暫存，離開前請先儲存。" : "Local storage unavailable. Save before leaving."); } }
  function fresh() { if ((form.name || form.notes || form.answers.some(Boolean)) && !window.confirm(zh ? "放棄尚未儲存的修改？" : "Discard unsaved changes?")) return; setEditing(null); requestId.current = crypto.randomUUID(); change(blank(form.stage), null); setError(""); name.current?.focus(); }
  function selectStage(stage: InsightStage) { if (stage === form.stage) return; const next = blank(stage); change({ ...next, ...(form.actionId ? { actionId: form.actionId } : {}), ...(form.challenge ? { challenge: form.challenge } : {}), name: form.name, company: form.company, role: form.role, notes: [...form.answers.map((v, i) => v ? `${STAGE_CONFIG[form.stage].fields[i][lang]}: ${v}` : "").filter(Boolean), form.notes].filter(Boolean).join("\n\n"), region: form.region, industry: form.industry, date: form.date }); }
  const config = STAGE_CONFIG[form.stage], records = rows.flatMap(row => { const p = insightSchema.safeParse(row.insight); return p.success && (!actionId || p.data.actionId === actionId) ? [{ id: row.id, updatedAt: row.updatedAt, data: p.data }] : []; }), stageRows = records.filter(row => Boolean(actionId) || row.data.stage === form.stage);
  const latest = editing ? records.find(row => row.id === editing.id) : undefined;
  const field = "mt-1 min-h-11 w-full rounded-lg border border-dark/15 bg-white px-3 py-2 text-sm placeholder:text-dark/35 focus-visible:outline-2 focus-visible:outline-offset-2";
  const button = "inline-flex min-h-11 items-center justify-center rounded-lg border border-dark/20 px-4 py-2 text-sm font-medium disabled:opacity-50";
  return <section className="space-y-5" aria-label={zh ? "分階段客戶探索" : "Customer discovery by stage"}>
    <div className="flex flex-wrap items-center justify-between gap-3">{!actionId && <div className="flex flex-wrap gap-1" role="group" aria-label={zh ? "訪談階段" : "Conversation stage"}>{INSIGHT_STAGES.map((stage, i) => <button type="button" key={stage} disabled={busy || !loaded || readOnly} aria-pressed={form.stage === stage} onClick={() => selectStage(stage)} className={`${button} ${form.stage === stage ? "bg-black text-white" : "bg-white text-dark/60"}`}>{i + 1} · {STAGE_CONFIG[stage].title[lang]}</button>)}</div>}<button type="button" className={button} disabled={busy || readOnly} onClick={fresh}>+ {zh ? "記錄對話" : "Log a conversation"}</button></div>
    {editing && <p role="status" className="text-sm">{zh ? "正在編輯已儲存對話" : "Editing a saved conversation"}<button type="button" className={`${button} ml-3`} onClick={fresh}>{zh ? "取消編輯" : "Cancel edit"}</button></p>}
    {!actionId && <CustomerStageGoal key={form.stage} stage={form.stage} people={uniqueStagePeople(form.stage, rows.map(r => r.insight))} confirmed={outcomes.find(o => o.stage === form.stage)} />}
    <form onSubmit={async e => { e.preventDefault(); if (sending.current) return; sending.current = true; setBusy(true); setError(""); setConflict(false); setNotice(""); try { const parsed = insightSchema.safeParse(form); if (!parsed.success) throw new Error(parsed.error.issues.map(i => `${i.path.join(".")}: ${i.message}`).join("; ")); const res = await fetch("/api/customer-insights", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { ...editing, insight: form } : { requestId: requestId.current, insight: form }) }); const json = await res.json(); if (!res.ok) { if (res.status === 409) { setConflict(true); onSaved?.(); router.refresh(); } throw new Error(json.error || `HTTP ${res.status}`); } requestId.current = crypto.randomUUID(); setEditing(null); change(blank(form.stage), null); setNotice(zh ? "對話已儲存。" : "Conversation saved."); notifyPlanChanged(userId); onSaved?.(json.data?.plan); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { sending.current = false; setBusy(false); } }} className={`grid gap-4 ${actionId ? "sm:grid-cols-2" : "lg:grid-cols-[minmax(0,1fr)_minmax(0,1.65fr)]"}`}>
      <fieldset disabled={busy || !loaded || readOnly} className="min-w-0 space-y-4 rounded-xl border border-dark/15 bg-white p-5"><legend className="px-1 font-semibold">{zh ? "與誰對話" : "Who you spoke with"}</legend>
        {(["name", "company", "role"] as const).map((key, i) => <label key={key} className="block text-sm font-medium">{(zh ? ["姓名", "公司", "角色"] : ["Name", "Company", "Role"])[i]}<input ref={key === "name" ? name : undefined} required={key === "name" || (key === "company" && Boolean(form.actionId))} maxLength={200} value={form[key]} placeholder={(zh ? ["例：Vivian Lee", "例：Acme AI", "例：創辦人"] : ["e.g. Vivian Lee", "e.g. Acme AI", "e.g. Founder"])[i]} className={field} onChange={e => change({ ...form, [key]: e.target.value })} /></label>)}
        <label className="block text-sm font-medium">{zh ? "主要挑戰（選填）" : "Main challenge (optional)"}<select value={form.challenge ?? ""} className={field} onChange={e => { const next = { ...form }; if (e.target.value) next.challenge = e.target.value as Insight["challenge"]; else delete next.challenge; change(next); }}><option value="">{zh ? "未分類" : "Unclassified"}</option>{Object.entries(CHALLENGES).map(([key, labels]) => <option key={key} value={key}>{labels[lang]}</option>)}</select></label>
        {!actionId && <label className="block text-sm font-medium">{zh ? "對話類型" : "Conversation type"}<select value={form.type} className={field} onChange={e => change({ ...form, type: e.target.value })}>{config.types.map(type => <option key={type} value={type}>{zh ? ({ Prospect: "潛在客戶", "Industry expert": "產業專家", Mentor: "導師", Internal: "內部人員", User: "使用者", Buyer: "買方", "Decision maker": "決策者", Partner: "合作夥伴", Angel: "天使投資人", "VC scout": "創投代表", Advisor: "顧問", "Customer reference": "客戶推薦人" } as Record<string, string>)[type] : type}</option>)}</select></label>}
        <label className="block text-sm font-medium">{form.stage === "angel_round" ? (zh ? "符合投資主題？" : "Thesis fit?") : (zh ? "符合我的 ICP？" : "Fits my ICP?")}<select value={form.fit} onChange={e => change({ ...form, fit: e.target.value as Insight["fit"] })} className={field}>{(["unknown", "yes", "partly", "no"] as const).map((fit, i) => <option key={fit} value={fit}>{(zh ? ["尚未確認", "是", "部分符合", "否"] : ["Not sure yet", "Yes", "Partly", "No"])[i]}</option>)}</select></label>
      </fieldset>
      <fieldset disabled={busy || !loaded || readOnly} className="min-w-0 rounded-xl border border-dark/15 bg-white p-5"><legend className="px-1 font-semibold">{zh ? "記錄你聽到的事" : "Capture what you heard"}</legend><div className={`grid gap-4 ${actionId ? "" : "sm:grid-cols-2"}`}>{config.fields.map((label, i) => <label key={`${form.stage}-${i}`} className="text-sm font-medium">{label[lang]}<textarea rows={4} maxLength={4000} value={form.answers[i]} placeholder={zh ? "只記錄對方實際提到的內容；未知可留白" : "What they actually said; leave unknown details blank"} className={field} onChange={e => change({ ...form, answers: form.answers.map((value, index) => index === i ? e.target.value : value) })} /></label>)}</div>
        <details className="mt-4"><summary className="flex min-h-11 cursor-pointer items-center text-sm font-medium">{zh ? "更多資訊與原始筆記" : "More details and original notes"}</summary><div className="space-y-3">{(["region", "industry", "date"] as const).map((key, i) => <label key={key} className="block text-sm">{(zh ? ["地區", "產業", "日期"] : ["Region", "Industry", "Date"])[i]}<input type={key === "date" ? "date" : "text"} maxLength={200} value={form[key]} className={field} onChange={e => change({ ...form, [key]: e.target.value })} /></label>)}<label className="block text-sm">{zh ? "原始筆記" : "Original notes"}<textarea rows={4} maxLength={8000} value={form.notes} className={field} onChange={e => change({ ...form, notes: e.target.value })} /></label></div></details>
        <button disabled={busy || !loaded || readOnly} className={`${button} mt-4 bg-black text-white`}>{busy ? (zh ? "儲存中…" : "Saving…") : (zh ? "儲存對話" : "Save conversation")}</button>
      </fieldset>
    </form>
    {error && <div role="alert" className="whitespace-pre-wrap rounded-xl bg-red-50 p-4 text-sm text-red-700"><p>{error}</p>{conflict && latest && latest.updatedAt !== editing?.updatedAt && <><p className="mt-2">{zh ? "輸入已保留。請先展開下方最新紀錄比較，再確認是否用目前輸入取代。" : "Your input is retained. Expand the latest conversation below to compare before replacing it."}</p><button type="button" className={`${button} mt-2`} disabled={busy || readOnly} onClick={() => { if (!window.confirm(zh ? "已比較最新紀錄？下次儲存將用目前輸入取代此版本。" : "Have you reviewed the latest record? The next save will replace it with your current input.")) return; const edit = { id: latest.id, updatedAt: latest.updatedAt }; setEditing(edit); change(form, edit); setConflict(false); setError(""); setNotice(zh ? "已載入最新版本，輸入保留；請審閱後再次儲存。" : "Latest version loaded; input retained. Review and save again."); }}>{zh ? "已比較，使用最新版本重試" : "Compared; retry with latest version"}</button></>}</div>}{notice && <p role="status" className="text-sm">{notice}</p>}
    {!actionId && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-dark/10 bg-white p-4"><p className="text-sm">{zh ? "從真實對話整理 ICP，儲存前由你確認。" : "Shape your ICP from real conversations. You confirm before saving."}</p><Link className={button} href={`${pathForLocale("/dashboard/profile", locale)}#icp-start`}>{zh ? "使用 POLARIS 整理 ICP" : "Sharpen my ICP"} →</Link></div>}
    {stageRows.length > 0 && <section><h2 className="font-semibold">{zh ? "本階段對話紀錄" : "Conversations in this stage"}</h2><div className="mt-3 space-y-2">{stageRows.map(({ id, updatedAt, data }) => <details key={id} className="rounded-xl border border-dark/10 bg-white p-4"><summary className="min-h-11 cursor-pointer font-medium">{data.name}{data.company ? ` · ${data.company}` : ""}{data.date ? ` · ${data.date}` : ""}</summary><dl className="mt-3 space-y-3 text-sm">{data.answers.map((answer, i) => <div key={i}><dt className="text-dark/60">{STAGE_CONFIG[data.stage].fields[i][lang]}</dt><dd className="whitespace-pre-wrap">{answer || (zh ? "尚未記錄" : "Not recorded")}</dd></div>)}{data.notes && <div><dt>{zh ? "原始筆記" : "Original notes"}</dt><dd className="whitespace-pre-wrap">{data.notes}</dd></div>}</dl><button type="button" disabled={busy || readOnly} className={`${button} mt-3`} onClick={() => { if ((form.name || form.notes || form.answers.some(Boolean)) && !window.confirm(zh ? "放棄尚未儲存的修改並開啟這筆對話？" : "Discard unsaved changes and edit this conversation?")) return; const edit = { id, updatedAt }; setEditing(edit); change(data, edit); setError(""); name.current?.focus(); name.current?.scrollIntoView({ block: "center" }); }}>{zh ? "編輯對話" : "Edit conversation"}</button><button type="button" disabled={busy || readOnly} className={`${button} ml-2 mt-3 text-red-700`} onClick={async () => { if (!window.confirm(zh ? "刪除這筆訪談紀錄？" : "Delete this conversation?")) return; setBusy(true); setError(""); try { const res = await fetch(`/api/notes/${id}?updatedAt=${encodeURIComponent(updatedAt)}`, { method: "DELETE" }); const json = await res.json(); if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`); if (editing?.id === id) { setEditing(null); requestId.current = crypto.randomUUID(); change(blank(form.stage), null); } onSaved?.(); notifyPlanChanged(userId); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); onSaved?.(); router.refresh(); } finally { setBusy(false); } }}>{zh ? "刪除" : "Delete"}</button></details>)}</div></section>}
  </section>;
}
