"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { EMPTY_GUESS, guessSchema, guessToIcp, type IcpGuess, type DiscoveryState, type DiscoveryInput } from "@/lib/icp/discovery";
import { EMPTY_ICP, type IcpWorkspaceView } from "@/lib/icp/schema";
import type { Locale } from "@/i18n/routing";
import { pathForLocale } from "@/lib/routes";
import { notifyPlanChanged } from "./PlanRefresh";
const examples = {
  en: ["Founder of a 1–10 person AI or SaaS startup", "Not knowing who to sell to or what to do next", "They have an MVP but no paying customers", "Use ChatGPT, spreadsheets, and cold emails"],
  "zh-tw": ["1–10 人 AI 或 SaaS 新創的創辦人", "不知道該賣給誰、下一步該做什麼", "已有 MVP，但還沒有付費客戶", "使用 ChatGPT、試算表與陌生開發郵件"],
};
export default function IcpDiscovery({ userId, canUseAi, onUpdated }: { userId: string; canUseAi: boolean; onUpdated: (view: IcpWorkspaceView) => void }) {
  const locale = useLocale() as Locale, zh = locale === "zh-tw", router = useRouter();
  const [workspace, setWorkspace] = useState<IcpWorkspaceView | null>(null), [path, setPath] = useState<DiscoveryState["path"] | null>(null), [guess, setGuess] = useState<IcpGuess>({ ...EMPTY_GUESS }), [product, setProduct] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const sending = useRef(false), pendingRequest = useRef<{ id: string; payload: string } | null>(null), fieldRef = useRef<HTMLInputElement>(null);
  const key = `nova:icp-discovery:${userId}`;
  const accept = useCallback((v: IcpWorkspaceView) => { setWorkspace(v); onUpdated(v); }, [onUpdated]);
  async function request(method = "GET", data?: object) { const res = await fetch(`/api/account/icp?locale=${locale}`, { method, cache: "no-store", ...(data ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) } : {}) }); let json; try { json = await res.json(); } catch { throw new Error(`HTTP ${res.status}`); } if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`); return json.data as IcpWorkspaceView; }
  async function reload(restore = false) { try { const next = await request(); accept(next); if (restore) { const d = next.discovery; setPath(d?.path || null); setGuess(d?.guess || d?.input?.guess || EMPTY_GUESS); setProduct(d?.input?.product || ""); try { const cached = JSON.parse(localStorage.getItem(key) || "null"); if (cached && ["guess", "suggest", "discovery"].includes(cached.path)) { const parsed = guessSchema.safeParse(cached.guess); if (parsed.success) { setPath(cached.path); setGuess(parsed.data); setProduct(typeof cached.product === "string" ? cached.product.slice(0, 600) : ""); } } } catch { setNotice(zh ? "無法恢復本機輸入。" : "Local input could not be restored."); } } return next; } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  useEffect(() => { const timer = setTimeout(() => void reload(true), 0); return () => clearTimeout(timer); /* restore only on account/locale change */ // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, locale]);
  useEffect(() => { if (!workspace?.pending) return; const timer = setInterval(() => void reload(), 3000); return () => clearInterval(timer); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspace?.pending]);
  function remember(nextPath: DiscoveryState["path"] | null, nextGuess = guess, nextProduct = product) { try { localStorage.setItem(key, JSON.stringify({ path: nextPath, guess: nextGuess, product: nextProduct })); } catch { setNotice(zh ? "無法暫存輸入，請在離開前儲存。" : "Local storage unavailable. Save before leaving."); } }
  async function mutate(action: "choose" | "save" | "discover", selectedPath: DiscoveryState["path"], mode?: DiscoveryInput["mode"]) {
    if (sending.current || !workspace || workspace.pending) return;
    sending.current = true; setBusy(true); setError(""); setNotice("");
    const discovery: DiscoveryState = { path: selectedPath, guess };
    const content = { action, revision: workspace.revision, profileVersion: workspace.profileVersion, locale, ...(action === "discover" ? { discovery: { mode, guess, product } } : { discovery, draft: action === "choose" ? EMPTY_ICP : guessToIcp(guess, workspace.saved || EMPTY_ICP) }) };
    if (action === "discover") delete (content as { profileVersion?: number }).profileVersion;
    const payload = JSON.stringify(content);
    if (pendingRequest.current?.payload !== payload) pendingRequest.current = { id: crypto.randomUUID(), payload };
    try {
      const next = await request(action === "discover" ? "POST" : "PATCH", { ...content, requestId: pendingRequest.current!.id }); accept(next); pendingRequest.current = null;
      setPath(selectedPath); remember(selectedPath);
      if (action === "save") { setNotice(zh ? "ICP 初始假設已儲存至 Profile。" : "Your first ICP guess is saved to Profile."); try { localStorage.removeItem(key); } catch { /* Saved on server. */ } notifyPlanChanged(userId); router.refresh(); }
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); await reload(); }
    finally { sending.current = false; setBusy(false); }
  }
  const disabled = busy || !workspace || workspace.pending, result = workspace?.discovery?.result;
  const button = "inline-flex min-h-11 items-center justify-center rounded-lg border border-dark/20 px-4 py-2 text-sm font-medium disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2";
  const field = "mt-2 min-h-11 w-full rounded-lg border border-dark/15 bg-white px-3 py-3 text-sm text-dark placeholder:text-dark/40 focus-visible:outline-2 focus-visible:outline-offset-2";
  return <div id="icp-start" className="scroll-mt-8">
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-semibold uppercase tracking-wider">{zh ? "你的 ICP" : "Your ICP"}</h2><span className="rounded-full bg-dark/5 px-3 py-1 text-xs text-dark/60">{path === "discovery" ? (zh ? "尚未定義" : "Not defined yet") : (zh ? "初始假設" : "Draft guess")}</span></div>
    <p className="mt-3 text-sm text-dark/60">{zh ? "先寫一個大致方向，再用真實客戶對話修正。不確定也可以開始。" : "Start with a rough guess. Test it through real conversations. It is OK not to know yet."}</p>
    <div className="mt-4 flex flex-wrap gap-2" role="group" aria-label={zh ? "選擇 ICP 起點" : "Choose your ICP starting point"}>{(["guess", "suggest", "discovery"] as const).map((value, i) => <button key={value} type="button" aria-pressed={path === value} disabled={disabled} className={`${button} ${path === value ? "bg-black text-white" : "bg-white"}`} onClick={() => { setPath(value); remember(value); void mutate("choose", value); }}>{(zh ? ["我有初步想法", "不確定適合誰", "還沒有想法"] : ["I have a guess", "Not sure who it’s for", "No idea yet"])[i]}</button>)}</div>
    {path === "guess" && <div className="mt-5 space-y-4"><div><h3 className="text-lg font-semibold">{zh ? "完成這句話" : "Finish this sentence"}</h3><p className="mt-1 text-sm text-dark/60">{zh ? "大致方向就可以，之後透過對話驗證。" : "Rough is fine. You’ll test it with real conversations."}</p></div>{(["customer", "struggle", "situation", "workaround"] as const).map((keyName, i) => <label key={keyName} className="block text-sm font-medium">{(zh ? ["我的客戶是", "他們的困難是", "發生在", "他們目前會"] : ["My customer is", "who struggles with", "when", "and today they"])[i]}<input ref={i === 0 ? fieldRef : undefined} maxLength={500} disabled={disabled} value={guess[keyName]} placeholder={examples[locale][i]} className={field} onChange={event => { const next = { ...guess, [keyName]: event.target.value }; setGuess(next); remember(path, next); }} /></label>)}
      <div className="flex flex-wrap gap-2"><button type="button" disabled={disabled || !guess.customer.trim() || !guess.struggle.trim()} className={`${button} bg-black text-white`} onClick={() => void mutate("save", "guess")}>{zh ? "儲存初始假設" : "Save draft guess"}</button>{canUseAi && <button type="button" disabled={disabled || !guess.customer.trim() && !guess.struggle.trim()} className={button} onClick={() => void mutate("discover", "guess", "sharpen")}>✧ {zh ? "請 POLARIS 聚焦" : "Sharpen with POLARIS"}</button>}</div></div>}
    {path === "suggest" && <div className="mt-5"><h3 className="text-lg font-semibold">{zh ? "你覺得誰會需要它？" : "Who do you think this is for?"}</h3><label className="mt-3 block text-sm">{zh ? "用一句話描述產品" : "Describe your product in one sentence"}<textarea rows={3} maxLength={600} disabled={disabled} value={product} className={field} placeholder={zh ? "例如：協助早期新創決定向誰銷售、下一步做什麼的 AI 工具" : "An AI tool that tells early startups who to sell to and what to do next"} onChange={e => { setProduct(e.target.value); remember(path, guess, e.target.value); }} /></label>{canUseAi && <button type="button" disabled={disabled || product.trim().length < 10} className={`${button} mt-3`} onClick={() => void mutate("discover", "suggest", "suggest")}>{result?.candidates.length ? (zh ? "提供其他候選方向" : "Show me other options") : (zh ? "建議可能的客戶" : "Suggest possible customers")}</button>}</div>}
    {path === "discovery" && <div className="mt-5"><h3 className="text-lg font-semibold">{zh ? "從最初幾次對話開始建立" : "We’ll build it from your first conversations"}</h3><ol className="mt-4 space-y-3 text-sm"><li>1. {zh ? "與 10 位可能有需求的人聊聊。" : "Talk to 10 people who might need your product."}</li><li>2. {zh ? "讓 POLARIS 整理重複出現的問題。" : "Let POLARIS find recurring problems."}</li><li>3. {zh ? "你確認後，才儲存第一份 ICP。" : "You review and save your first ICP."}</li></ol><p className="mt-4 text-sm text-dark/60">{zh ? `已保存 ${workspace?.customerConversationCount ?? 0} 次含筆記的客戶對話；至少 5 次可整理草稿。` : `${workspace?.customerConversationCount ?? 0} customer conversations with notes saved; at least 5 are needed for a draft.`}</p><div className="mt-4 flex flex-wrap gap-2"><Link className={`${button} bg-black text-white`} href={pathForLocale("/dashboard/insights", locale)}>{zh ? "記錄客戶對話" : "Log a conversation"}</Link>{canUseAi && <button type="button" disabled={disabled || (workspace?.customerConversationCount ?? 0) < 5} className={button} onClick={() => void mutate("discover", "discovery", "synthesize")}>{zh ? "整理客戶對話" : "Find patterns with POLARIS"}</button>}</div></div>}
    {!canUseAi && <Link className={`${button} mt-4`} href={pathForLocale("/dashboard/account#plan", locale)}>{zh ? "AI 分析需 Pro 以上方案" : "AI analysis requires Pro or above"}</Link>}
    {result && workspace?.discovery?.path === path && <section className="mt-5 space-y-3 rounded-xl border border-sky-200 bg-sky-50/40 p-4"><h3 className="font-semibold">POLARIS</h3><p className="whitespace-pre-wrap text-sm">{result.message}</p>{result.question && <p className="text-sm font-semibold">{result.question}</p>}{result.candidates.map(candidate => <div key={candidate.name} className="rounded-xl border border-dark/10 bg-white p-4"><h4 className="font-semibold">{candidate.name}</h4><span className="mt-2 inline-block rounded-full bg-dark/5 px-2 py-1 text-xs">{(zh ? { easy: "容易接觸", some_effort: "需要一些努力", hard: "較難接觸" } : { easy: "Easy to reach", some_effort: "Some effort", hard: "Hard to reach" })[candidate.reach]}</span><p className="mt-2 text-sm">{candidate.whyFirst}</p><p className="mt-2 text-sm text-dark/60">{zh ? "建議接觸管道" : "Suggested channels"}: {candidate.whereToFind.join(" · ")}</p><p className="mt-2 text-sm">{zh ? "待驗證的假設" : "Assumption to test"}: {candidate.assumptionToTest}</p><button type="button" disabled={disabled} className={`${button} mt-3`} onClick={() => { setGuess(candidate.guess); setPath("guess"); remember("guess", candidate.guess); }}>{zh ? "作為初始假設並編輯" : "Use as my first guess"}</button></div>)}{result.guess && <><dl className="space-y-2 text-sm">{Object.entries(result.guess).map(([k, v], i) => <div key={k}><dt className="text-dark/60">{(zh ? ["客戶", "問題", "情境", "现有解法"] : ["Customer", "Problem", "Situation", "Workaround"])[i]}</dt><dd>{v || (zh ? "尚未確認" : "Not confirmed")}</dd></div>)}</dl><button type="button" disabled={disabled} className={button} onClick={() => { setGuess(result.guess!); setPath("guess"); remember("guess", result.guess!); }}>{zh ? "編輯這份草稿" : "Edit this draft"}</button></>}{result.patterns.map(p => <div key={p.text} className="text-sm"><p className="font-semibold">{p.text}</p>{p.evidence.map(e => <blockquote key={e.id} className="mt-2 border-l-2 pl-3 text-dark/60">“{e.quote}”</blockquote>)}</div>)}{result.unclear.length > 0 && <p className="text-sm text-dark/60">{zh ? "尚待確認" : "Still unclear"}: {result.unclear.join(" · ")}</p>}</section>}
    {(busy || workspace?.pending) && <p role="status" className="mt-4 text-sm">{zh ? "處理中，請稍候。AI 分析約需一分鐘。" : "Working… AI analysis can take about a minute."}</p>}
    {(error || workspace?.error) && <div role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700"><p className="whitespace-pre-wrap">{error || workspace?.error}</p><button type="button" disabled={busy} className={`${button} mt-2`} onClick={() => { setError(""); void reload(); }}>{zh ? "重新載入工作區（保留輸入）" : "Reload workspace (keep input)"}</button></div>}{notice && <p role="status" className="mt-3 text-sm">{notice}</p>}
  </div>;
}
