"use client";
import { useEffect, useRef, useState } from "react";
import { useLocale } from "next-intl";
import type { ActionPlanDto } from "@/lib/action-plan/service";
import type { ActionPlanActionDto } from "@/lib/action-plan/ranking";
import { emptyWorkspace, workspaceSchema, workspaceKind, workspaceProgress, leadScore, findingSchema, findingDraftSchema, type TaskWorkspace as Workspace, type WorkspaceLead } from "@/lib/action-plan/workspace";
import InterviewWorkspace from "./InterviewWorkspace";
import LearningResources from "./LearningResources";

const button = "inline-flex min-h-11 items-center justify-center rounded-lg border border-dark/20 px-4 py-2 text-sm font-semibold disabled:opacity-50";
const input = "mt-1 min-h-11 w-full rounded-lg border border-dark/15 bg-white px-3 py-2 text-sm placeholder:text-dark/35 focus-visible:outline-2 focus-visible:outline-offset-2";
const card = "min-w-0 rounded-xl border border-dark/15 bg-white p-4";
const questions = {
  icp: ["How to define an ICP?", "如何定義 ICP？"], pilot: ["How to offer a paid pilot?", "如何提出付費試用？"], positioning: ["How to write a positioning statement?", "如何撰寫定位句？"], scorecard: ["How to build a lead scorecard?", "如何建立潛客評分卡？"], tiers: ["How to segment and tier leads?", "如何將潛客分群與分級？"],
} as const;

export default function TaskWorkspace({ userId, action, plan, busy, onChanged, onInsights, onAnalyze }: { userId: string; action: ActionPlanActionDto; plan: ActionPlanDto; busy: boolean; onChanged: (plan: ActionPlanDto | null) => void; onInsights: () => void; onAnalyze: () => void }) {
  const kind = workspaceKind(action);
  return <>{kind === "interview" ? <InterviewWorkspace userId={userId} action={action} busy={busy} onChanged={onChanged} onInsights={onInsights} /> : kind ? <WorkspaceForm key={action.id} userId={userId} action={action} plan={plan} busy={busy} onChanged={onChanged} /> : null}
    {kind && <TaskFinding userId={userId} action={action} plan={plan} busy={busy} onChanged={onChanged} onAnalyze={onAnalyze} />}
  </>;
}

function WorkspaceField({ label, value, placeholder, onChange, area = false }: { label: string; value: string; placeholder: string; onChange: (value: string) => void; area?: boolean }) {
  return <label className="block min-w-0 text-xs font-medium text-dark/65">{label}{area ? <textarea rows={3} value={value} maxLength={2000} placeholder={placeholder} onChange={e => onChange(e.target.value)} className={input} /> : <input value={value} maxLength={2000} placeholder={placeholder} onChange={e => onChange(e.target.value)} className={input} />}</label>;
}

function WorkspaceForm({ userId, action, plan, busy, onChanged }: { userId: string; action: ActionPlanActionDto; plan: ActionPlanDto; busy: boolean; onChanged: (plan: ActionPlanDto | null) => void }) {
  const zh = useLocale() === "zh-tw", lang = zh ? 1 : 0;
  const kind = workspaceKind(action) as Exclude<keyof typeof questions, "interview">;
  const [form, setForm] = useState<Workspace>(() => action.taskWorkspace || emptyWorkspace(kind));
  const [baseRevision, setBaseRevision] = useState(plan.revision ?? 0);
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [saving, setSaving] = useState(false), [loaded, setLoaded] = useState(false), [conflict, setConflict] = useState(false);
  const [leads, setLeads] = useState<WorkspaceLead[]>([]), [criteria, setCriteria] = useState<Extract<Workspace, { kind: "scorecard" }>["criteria"]>([]);
  const [evidenceLoaded, setEvidenceLoaded] = useState(false);
  const sending = useRef(false), dirty = useRef(false), key = `nova:task-workspace:${userId}:${action.id}`;
  useEffect(() => { const timer = setTimeout(() => {
    try { const cached = JSON.parse(localStorage.getItem(key) || "null"), parsed = workspaceSchema.safeParse(cached?.form); if (parsed.success && parsed.data.kind === kind && Number.isInteger(cached.revision)) { setForm(parsed.data); setBaseRevision(cached.revision); dirty.current = true; } }
    catch { setNotice(zh ? "無法恢復本機草稿，已存資料保留。" : "Local draft could not be restored; saved data retained."); }
    setLoaded(true);
  }, 0); return () => clearTimeout(timer); }, [key, kind, zh]);
  useEffect(() => { const timer = setTimeout(() => { if (!dirty.current) { setForm(action.taskWorkspace || emptyWorkspace(kind)); setBaseRevision(plan.revision ?? 0); } }, 0); return () => clearTimeout(timer); }, [action.taskWorkspace, kind, plan.revision]);
  async function loadEvidence() {
    const res = await fetch(`/api/customer-insights?actionId=${encodeURIComponent(action.id)}&scope=plan`, { cache: "no-store" });
    const json = await res.json(); if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
    return json.data as { leads: WorkspaceLead[]; scorecards: Array<{ criteria: typeof criteria }> };
  }
  useEffect(() => {
    if (kind !== "pilot" && kind !== "tiers") return;
    let alive = true;
    void loadEvidence().then(data => { if (alive) { setLeads(data.leads); setCriteria(data.scorecards[0]?.criteria || []); setEvidenceLoaded(true); } }).catch(cause => { if (alive) setError(cause instanceof Error ? cause.message : String(cause)); });
    return () => { alive = false; };
    // Evidence refresh never replaces the user's draft.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [action.id, kind, plan.revision]);
  const disabled = busy || saving || !loaded || action.done || action.dependency.blocked;
  function change(next: Workspace) { const revision = dirty.current ? baseRevision : plan.revision ?? 0; if (!dirty.current) setBaseRevision(revision); dirty.current = true; setForm(next); setNotice(""); try { localStorage.setItem(key, JSON.stringify({ form: next, revision })); } catch { setNotice(zh ? "草稿無法暫存，離開前請先儲存。" : "Draft storage unavailable; save before leaving."); } }
  
  const leadOptions = <><option value="">{zh ? "選擇已訪談潛客" : "Choose an interviewed prospect"}</option>{leads.map(l => <option key={l.id} value={l.id}>{l.name} · {l.company}</option>)}</>;
  const progress = workspaceProgress(action.taskWorkspace || emptyWorkspace(kind));
  async function save(e: React.FormEvent) {
    e.preventDefault(); if (sending.current) return; sending.current = true; setSaving(true); setError(""); setConflict(false);
    try {
      const data = form.kind === "tiers" ? { ...form, leads: leads.map(l => form.leads.find(saved => saved.leadId === l.id) || { leadId: l.id, tier: "", segment: "", matches: [] }) } : form;
      const parsed = workspaceSchema.safeParse(data);
      if (!parsed.success) throw new Error(parsed.error.issues.map(i => `${i.path.join(".")}: ${i.message}`).join("; "));
      const res = await fetch(`/api/action-plans/actions/${action.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ revision: dirty.current ? baseRevision : plan.revision ?? 0, taskWorkspace: parsed.data }) });
      const json = await res.json(); if (!res.ok) { if (res.status === 409) setConflict(true); throw new Error(json.error || `HTTP ${res.status}`); }
      const next = json.data as ActionPlanDto;
      dirty.current = false; setBaseRevision(next.revision ?? 0); setForm(next.actions.find(a => a.id === action.id)?.taskWorkspace || parsed.data); onChanged(next);
      try { localStorage.removeItem(key); } catch { setNotice(zh ? "已儲存，但本機草稿清除失敗。" : "Saved; local draft cleanup failed."); }
      setNotice(zh ? "已儲存。確認內容後，勾選完成任務。" : "Saved. Review the records, then check off the task.");
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); }
    finally { sending.current = false; setSaving(false); }
  }
  return <section className="mt-5 space-y-4">
    <LearningResources question={questions[kind][lang]} />
    {(kind === "icp" || kind === "pilot") && <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-semibold">{kind === "icp" ? (zh ? "已寫好的候選 ICP" : "Possible ICPs written") : (zh ? "同意付費試用" : "Agreed to a paid pilot")} · {progress.current}/{kind === "pilot" ? form.kind === "pilot" ? form.prospects.length : 3 : progress.target}{kind === "pilot" && <span className="ml-2 text-xs font-normal text-dark/55">{zh ? "（目標：至少 1 位）" : "(goal: at least 1)"}</span>}</p><progress aria-label={zh ? "已存紀錄進度" : "Saved record progress"} value={Math.min(progress.current, progress.target)} max={progress.target} className="mt-3 h-2 w-full [&::-webkit-progress-bar]:bg-dark/10 [&::-webkit-progress-value]:bg-black [&::-moz-progress-bar]:bg-black" /></div>}
    <form onSubmit={save} className="space-y-4"><fieldset disabled={disabled} className="min-w-0 space-y-4">
      {form.kind === "icp" && form.candidates.map((c, i) => <details key={i} open={i === 0} className={card}><summary className="flex min-h-11 cursor-pointer flex-wrap items-center gap-2 text-sm font-bold">{zh ? "ICP 候選" : "ICP candidate"} {i + 1}<span className="text-xs font-normal text-dark/45">{c.name || (zh ? "尚未填寫" : "Not filled in yet")}</span></summary><div className="mt-3 space-y-3">{<WorkspaceField label={zh ? "候選名稱" : "Candidate name"} value={c.name} placeholder={zh ? "例：種子輪 B2B SaaS 創辦人" : "e.g. Seed-stage B2B SaaS founders"} onChange={value => change({ ...form, candidates: form.candidates.map((old, n) => n === i ? { ...old, name: value } : old) })} />}<div className="grid gap-3 sm:grid-cols-3">{(["industry", "size", "role"] as const).map((key, n) => <div key={key}>{<WorkspaceField label={(zh ? ["產業", "公司規模", "角色／職稱"] : ["Industry", "Company size", "Role / job title"])[n]} value={c[key]} placeholder={(zh ? ["例：金融科技", "例：10–50 人", "例：營運主管"] : ["e.g. Fintech", "e.g. 10–50 employees", "e.g. Head of operations"])[n]} onChange={value => change({ ...form, candidates: form.candidates.map((old, n) => n === i ? { ...old, [key]: value } : old) })} />}</div>)}</div><div className="grid gap-3 sm:grid-cols-2">{(["pain", "trigger"] as const).map((key, n) => <div key={key}>{<WorkspaceField label={(zh ? ["主要痛點", "購買觸發點（為何現在）"] : ["Main pain point", "Buying trigger (what makes them act now)"])[n]} value={c[key]} placeholder={(zh ? ["例：每週花 8 小時手動整理報表", "例：團隊擴大，需要統一流程"] : ["e.g. Eight hours of manual reporting weekly", "e.g. Team growth requires a shared process"])[n]} onChange={value => change({ ...form, candidates: form.candidates.map((old, n) => n === i ? { ...old, [key]: value } : old) })} area={true} />}</div>)}</div></div></details>)}
      {form.kind === "pilot" && <>{!leads.length && <p className="text-sm text-dark/60">{zh ? "先在本計畫儲存客戶訪談，潛客會出現在選單。" : "Save customer interviews in this plan to see prospects here."}</p>}{form.prospects.map((p, i) => <section key={i} className={card}><h4 className="text-sm font-bold">{zh ? "潛客" : "Prospect"} {i + 1}</h4><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs text-dark/65">{zh ? "潛客（來自訪談）" : "Prospect (from your interviews)"}<select className={input} value={p.leadId} onChange={e => change({ ...form, prospects: form.prospects.map((old, n) => n === i ? { ...old, leadId: e.target.value } : old) })}>{leadOptions}</select></label>{<WorkspaceField label={zh ? "試用方案與價格" : "Pilot offer & price"} value={p.offer} placeholder={zh ? "例：2 週試用，NT$3,000" : "e.g. Two-week pilot for $100"} onChange={value => change({ ...form, prospects: form.prospects.map((old, n) => n === i ? { ...old, offer: value } : old) })} />}<label className="text-xs text-dark/65">{zh ? "對方回應" : "Their response"}<select className={input} value={p.response} onChange={e => change({ ...form, prospects: form.prospects.map((old, n) => n === i ? { ...old, response: e.target.value as typeof p.response } : old) })}>{["", "agreed", "declined", "thinking"].map((v, n) => <option key={v} value={v}>{(zh ? ["選擇回應", "同意", "拒絕", "考慮中"] : ["Choose a response", "Agreed", "Declined", "Thinking"])[n]}</option>)}</select></label></div><div className="mt-3">{<WorkspaceField label={zh ? "為什麼？（原因或疑慮）" : "Why? (their reason or objection)"} value={p.reason} placeholder={zh ? "記錄對方實際的回應" : "Record their actual response"} onChange={value => change({ ...form, prospects: form.prospects.map((old, n) => n === i ? { ...old, reason: value } : old) })} area={true} />}</div></section>)}</>}
      {form.kind === "positioning" && <><section className={`${card} grid gap-4 sm:grid-cols-2`}>{(["who", "pain", "outcome", "how"] as const).map((key, n) => <div key={key}>{<WorkspaceField label={(zh ? ["你幫助誰（ICP）", "他們的痛點", "他們得到的成果", "你如何做到"] : ["Who you help (your ICP)", "Their pain", "The outcome they get", "How you deliver it"])[n]} value={form[key]} placeholder={(zh ? ["例：小型診所的經營者", "例：排程耗時又常衝突", "例：減少 50% 行政時間", "例：自動排程與通知"] : ["e.g. Independent clinic owners", "e.g. Time-consuming scheduling", "e.g. Less time on admin", "e.g. Automated scheduling and reminders"])[n]} onChange={value => change({ ...form, [key]: value })} />}</div>)}</section><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[11px] font-semibold uppercase text-dark/55">{zh ? "你的定位句（依上方內容組合）" : "Your sentence (from the boxes above)"}</p><p className="mt-2 text-sm font-bold">{zh ? `我們透過 ${form.how || "[方法]"}，幫助 ${form.who || "[對象]"} 解決 ${form.pain || "[痛點]"}，達成 ${form.outcome || "[成果]"}。` : `We help ${form.who || "[who]"} who ${form.pain || "[pain]"} to ${form.outcome || "[outcome]"} by ${form.how || "[how]"}.`}</p></div><section className={card}><h4 className="text-sm font-bold">{zh ? "驗證定位句" : "Validate it"}</h4><div className="mt-3 grid gap-4 sm:grid-cols-[1fr_2fr]"><label className="text-xs text-dark/65">{zh ? "測試對象數" : "Tested with (number of prospects)"}<input type="number" min={0} max={1000000} step={1} value={form.tested} className={input} onChange={e => change({ ...form, tested: Number(e.target.value) })} /></label>{<WorkspaceField label={zh ? "他們的反應（理解與困惑）" : "Their reaction (what made sense, what confused them)"} value={form.reaction} placeholder={zh ? "記錄實際回饋；未測試請留白" : "Actual feedback; leave blank until tested"} onChange={value => change({ ...form, reaction: value })} area={true} />}</div></section></>}
      {form.kind === "scorecard" && <section className={`${card} space-y-3`}>{form.criteria.map((c, i) => <div key={c.id} className="grid gap-3 border-b border-dark/5 pb-3 sm:grid-cols-[2fr_5rem_3fr]">{<WorkspaceField label={zh ? "條件" : "Criterion"} value={c.criterion} placeholder={zh ? "例：已付費使用類似工具" : "e.g. Pays for a similar tool today"} onChange={value => change({ ...form, criteria: form.criteria.map((old, n) => n === i ? { ...old, criterion: value } : old) })} />}<label className="text-xs text-dark/65">{zh ? "權重（1–5）" : "Weight (1–5)"}<input type="number" min={1} max={5} step={1} value={c.weight} className={input} onChange={e => change({ ...form, criteria: form.criteria.map((old, n) => n === i ? { ...old, weight: Number(e.target.value) } : old) })} /></label>{<WorkspaceField label={zh ? "什麼算符合" : "What counts as a fit"} value={c.fit} placeholder={zh ? "描述可觀察、可詢問的符合條件" : 'Describe what a "yes" looks like'} onChange={value => change({ ...form, criteria: form.criteria.map((old, n) => n === i ? { ...old, fit: value } : old) })} />}</div>)}<button type="button" className={button} disabled={form.criteria.length >= 20} onClick={() => change({ ...form, criteria: [...form.criteria, { id: crypto.randomUUID(), criterion: "", weight: 3, fit: "" }] })}>+ {zh ? "新增條件" : "Add criterion"}</button><p className="text-xs text-dark/55">{zh ? "最高分為所有權重總和" : "Maximum score = sum of all weights"}: {form.criteria.reduce((sum, c) => sum + c.weight, 0)}</p></section>}
      {form.kind === "tiers" && <section className={`${card} space-y-3`}>{!leads.length && <p className="text-sm text-dark/60">{zh ? "尚無本計畫的有效客戶訪談。" : "No valid customer interviews in this plan yet."}</p>}{!criteria.length && <p className="text-sm text-dark/60">{zh ? "先儲存完整評分卡，再依已確認條件計分。" : "Save a complete scorecard before scoring confirmed matches."}</p>}{leads.map(lead => {
        const value = form.leads.find(l => l.leadId === lead.id) || { leadId: lead.id, tier: "" as const, segment: "", matches: [] }, score = leadScore(value.matches, criteria);
        const update = (next: typeof value) => change({ ...form, leads: [...form.leads.filter(l => l.leadId !== lead.id), next] });
        return <div key={lead.id} className="space-y-3 border-b border-dark/10 pb-4"><div className="grid gap-3 sm:grid-cols-[2fr_5rem_5rem_2fr]"><div className="min-w-0"><p className="text-xs text-dark/55">{zh ? "潛客（來自訪談）" : "Lead (from interviews)"}</p><p className="mt-2 break-words text-sm font-semibold">{lead.name} · {lead.company}</p></div><div><p className="text-xs text-dark/55">{zh ? "自動分數" : "Score (auto)"}</p><p className="mt-2 text-sm font-semibold">{score.max ? `${score.score}/${score.max}` : "—"}</p></div><label className="text-xs text-dark/65">{zh ? "分級" : "Tier"}<select className={input} value={value.tier} onChange={e => update({ ...value, tier: e.target.value as typeof value.tier })}>{["", "A", "B", "C"].map(tier => <option key={tier} value={tier}>{tier || "—"}</option>)}</select></label>{<WorkspaceField label={zh ? "分群" : "Segment"} value={value.segment} placeholder={zh ? "例：初期 AI 工具團隊" : "e.g. Early-stage AI tools"} onChange={segment => update({ ...value, segment })} />}</div><details><summary className="flex min-h-11 cursor-pointer items-center text-xs font-semibold">{zh ? "確認符合的條件（未知不勾選）" : "Confirm matched criteria (leave unknown unchecked)"}</summary>{criteria.map(c => <label key={c.id} className="flex min-h-11 items-start gap-2 py-2 text-sm"><input type="checkbox" className="mt-1 h-5 w-5" checked={value.matches.includes(c.id)} onChange={e => update({ ...value, matches: e.target.checked ? [...value.matches, c.id] : value.matches.filter(id => id !== c.id) })} /><span>{c.criterion} · {c.weight}<span className="block text-xs text-dark/55">{c.fit}</span></span></label>)}</details></div>;
      })}<p className="text-xs text-dark/55">{zh ? "名單自動來自訪談；分數依已勾選條件加總。分級與分群由你確認。" : "Leads come from interviews; scores sum confirmed criteria. You choose the tier and segment."}</p></section>}
      <button disabled={disabled || ((kind === "pilot" || kind === "tiers") && !evidenceLoaded)} className={`${button} bg-black text-white`}>{saving ? (zh ? "儲存中…" : "Saving…") : ({ icp: ["Save ICP candidates", "儲存 ICP 候選"], pilot: ["Save pilot results", "儲存試用結果"], positioning: ["Save statement", "儲存定位句"], scorecard: ["Save scorecard", "儲存評分卡"], tiers: ["Save tiers", "儲存分級"] } as const)[kind][lang]}</button>
    </fieldset></form>
    {notice && <p role="status" className="text-sm">{notice}</p>}
    {error && <div role="alert" className="space-y-3 rounded-xl bg-red-50 p-4 text-sm text-red-700"><p className="whitespace-pre-wrap">{error}</p>{conflict && <button type="button" className={button} disabled={busy || saving} onClick={async () => { try { const res = await fetch("/api/action-plans/roadmap", { cache: "no-store" }), json = await res.json(); if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`); const next = json.data.active as ActionPlanDto | null; if (next?.id !== plan.id) throw new Error(zh ? "計畫已更換，草稿仍保留。" : "Plan changed; draft retained."); onChanged(next); const latest = next.actions.find(a => a.id === action.id); if (!window.confirm(`${zh ? "最新已存內容如下。保留目前输入，以此版本重試？" : "Latest saved records below. Keep your input and retry against this version?"}\n${JSON.stringify(latest?.taskWorkspace || {}, null, 2)}`)) return; setBaseRevision(next.revision ?? 0); localStorage.setItem(key, JSON.stringify({ form, revision: next.revision ?? 0 })); setConflict(false); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }}>{zh ? "比較最新版本並重試" : "Compare latest version and retry"}</button>}{(kind === "pilot" || kind === "tiers") && <button type="button" className={button} onClick={() => { void loadEvidence().then(data => { setLeads(data.leads); setCriteria(data.scorecards[0]?.criteria || []); setEvidenceLoaded(true); setError(""); }).catch(cause => setError(cause instanceof Error ? cause.message : String(cause))); }}>{zh ? "重新載入名單（保留輸入）" : "Reload leads (keep input)"}</button>}</div>}
  </section>;
}

function TaskFinding({ userId, action, plan, busy, onChanged, onAnalyze }: { userId: string; action: ActionPlanActionDto; plan: ActionPlanDto; busy: boolean; onChanged: (plan: ActionPlanDto | null) => void; onAnalyze: () => void }) {
  const zh = useLocale() === "zh-tw";
  const result = action.taskFinding?.result;
  const [edit, setEdit] = useState<typeof result>(null), [revision, setRevision] = useState(0), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const key = `nova:task-finding:${userId}:${action.id}`;
  useEffect(() => { if (!action.done) return; const timer = setTimeout(() => { try { const cached = JSON.parse(localStorage.getItem(key) || "null"), parsed = findingDraftSchema.safeParse(cached?.result); if (parsed.success && Number.isInteger(cached.revision)) { setEdit(parsed.data); setRevision(cached.revision); } } catch { setError(zh ? "無法恢復分析編輯草稿，已存分析仍保留。" : "Could not restore edits; saved findings retained."); } }, 0); return () => clearTimeout(timer); }, [key, action.done, zh]);
  function changeEdit(next: NonNullable<typeof result>) { setEdit(next); try { localStorage.setItem(key, JSON.stringify({ result: next, revision })); } catch { setError(zh ? "無法暫存修改，離開前請儲存。" : "Unable to store edits locally; save before leaving."); } }
  return <section className="mt-5 space-y-3 rounded-xl border border-slate-200 bg-slate-50 p-4" aria-label={zh ? "任務分析" : "Task findings"}>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-dark/55">{zh ? "完成任務後：AI Finding" : "After check-off: AI Finding"}{action.taskFinding?.source === "user" && <span className="ml-2">{zh ? "已人工編輯" : "Edited by you"}</span>}</p>{action.done && result && !edit && <button type="button" className={button} disabled={busy} onClick={() => { setEdit(result); setRevision(plan.revision ?? 0); setError(""); }}>{zh ? "編輯內容" : "Edit findings"}</button>}</div>
    {!result && <><div className="grid gap-3 sm:grid-cols-3">{[1, 2, 3].map(n => <div key={n} className="rounded-lg border border-dark/10 bg-white p-3"><p className="text-xs font-semibold">{zh ? "發現" : "Finding"} {n}</p><p className="mt-2 text-xs text-dark/55">{action.taskFinding?.pending ? (zh ? "分析中…" : "Analysing…") : (zh ? "儲存紀錄並完成任務後產生" : "Generated after saving and checking off")}</p></div>)}</div><p className="text-xs text-dark/55">{zh ? "根據此任務的真實紀錄產生三項發現與對你的意義；成功分析使用 1 次 AI 額度。" : "Three findings and their relevance, grounded in this task's saved records. A successful analysis uses 1 AI request."}</p>{action.done && <button type="button" disabled={busy || saving} className={button} onClick={onAnalyze}>{zh ? "產生／重試分析" : "Generate / retry findings"}</button>}</>}
    {result && !edit && <><div className="grid gap-3 sm:grid-cols-3">{result.cards.map((c, i) => <div key={i} className="min-w-0 rounded-lg border border-dark/10 bg-white p-3"><h4 className="text-xs font-semibold uppercase text-dark/60">{c.title}</h4><p className="mt-2 whitespace-pre-wrap text-sm">{c.text}</p>{c.evidence && <details className="mt-2 text-xs text-dark/50"><summary className="flex min-h-11 cursor-pointer items-center">{zh ? "原文依據" : "Saved evidence"}</summary><p className="whitespace-pre-wrap">{c.evidence}</p></details>}</div>)}</div><p className="whitespace-pre-wrap text-sm leading-6"><strong>{zh ? "對你的意義：" : "Why it matters to you: "}</strong>{result.why}</p></>}
    {edit && <form className="space-y-3" onSubmit={async e => { e.preventDefault(); if (saving) return; setSaving(true); setError(""); try { const parsed = findingSchema.parse(edit), res = await fetch(`/api/action-plans/actions/${action.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ finding: parsed, revision }) }), json = await res.json(); if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`); onChanged(json.data); setEdit(null); localStorage.removeItem(key); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setSaving(false); } }}><div className="grid gap-3 sm:grid-cols-3">{edit.cards.map((c, i) => <div key={i} className="space-y-2"><label className="block text-xs">{zh ? "標題" : "Title"}<input required maxLength={120} value={c.title} className={input} onChange={e => changeEdit({ ...edit, cards: edit.cards.map((old, n) => n === i ? { ...old, title: e.target.value } : old) })} /></label><label className="block text-xs">{zh ? "發現內容" : "Finding"}<textarea required rows={4} maxLength={1000} value={c.text} className={input} onChange={e => changeEdit({ ...edit, cards: edit.cards.map((old, n) => n === i ? { ...old, text: e.target.value } : old) })} /></label></div>)}</div><label className="block text-xs">{zh ? "對你的意義" : "Why it matters to you"}<textarea required maxLength={1500} rows={3} className={input} value={edit.why} onChange={e => changeEdit({ ...edit, why: e.target.value })} /></label><div className="flex gap-2"><button disabled={busy || saving} className={`${button} bg-black text-white`}>{zh ? "儲存修改" : "Save edits"}</button><button type="button" disabled={saving} className={button} onClick={() => { setEdit(null); try { localStorage.removeItem(key); } catch { setError(zh ? "本機草稿清除失敗。" : "Could not clear local draft."); } }}>{zh ? "取消" : "Cancel"}</button></div></form>}
    {(error || action.taskFinding?.error) && <div role="alert" className="space-y-2 text-sm text-red-700"><p className="whitespace-pre-wrap">{error || action.taskFinding?.error}</p>{edit && <button type="button" className={button} disabled={saving || busy} onClick={async () => { try { const res = await fetch("/api/action-plans/roadmap", { cache: "no-store" }), json = await res.json(); if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`); const next = json.data.active as ActionPlanDto | null; if (next?.id !== plan.id) throw new Error(zh ? "計畫已更換，修改仍保留。" : "Plan changed; edits retained."); onChanged(next); if (!window.confirm(`${zh ? "比較最新分析後，保留目前輸入重試？" : "Review the latest findings, then retry with your current edits?"}\n${JSON.stringify(next.actions.find(a => a.id === action.id)?.taskFinding?.result || {}, null, 2)}`)) return; setRevision(next.revision ?? 0); localStorage.setItem(key, JSON.stringify({ result: edit, revision: next.revision ?? 0 })); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }}>{zh ? "比較最新分析並重試" : "Compare latest findings and retry"}</button>}</div>}
  </section>;
}
